language: python
python:
- '3.6'
- '3.5'
install:
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script:
- mypy --ignore-missing-imports --follow-imports=skip --strict-optional --warn-no-return
  amundsenatlastypes
deploy:
- provider: pypi
  user: verdan
  password:
    secure: fTo/tDexpgKQ0MUwZzVoGvglOEqhWf/tjoV/zMDXOIv5dbMyJ+tW55BFCn+r/YZN5hvltDj8jmte74ggCrXHmXe+X+4mjZaak9+eobshc5CTal2JGZ8HBUYwZ5NIADMKodrhKDuT98cedIPePsW3z/AGQrJ6E1JmzlOxrbInNGpOdfy29If9ogd0b0e7FKz2exVcbxrqTT/rwo1aO0O60VeYfhVWs1qqrMuRLvdUl0hddmJz/FC6KEEEveSAl3WCoQhxfw//m8qJ68B3f0gS0J28F1/FivN64UzHiAwWkZlXlkhai1Ub+hAh5AxsmFt+5Ze9ZeTN3de+mFPAxYGHeIzzDjYcf37RLy6vxIfNh/p0LB3fZQNVyFx1BCWvfO0s7T78I3K6Bf4B8F6V3lV88sGdo2waIJxucuaeYi1qfkltAtFk8U3Cv5e1E4DJge7dhRhtgzlXSuYgeor5LZ9MJiN3rgysXZFShlHXSMV/NRDLw2beqqYWJirs4hU0UmP8CRv1xXvlyi9Vqdxk4Dfgbd41RhvPnx/wtc0yB6HFqDMZhBbAE5g0tgSFAyHTYby1+Tqdw6x3Oniw65gCI/mX4O2Pd/V6i93PkBKhMtjBRldHYGFyoTiXr63A6NYRds/eYWJQjz9kTkMKcf7F+dIjdPnP65YWEaGW0tS6ql2zBTw=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  server:
  on:
    tags: true
    repo: dwarszawski/amundsen-atlas-types