language: python
python:
- '3.6'
- '3.5'
install:
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script:
- mypy --ignore-missing-imports --follow-imports=skip --strict-optional --warn-no-return amundsenatlastypes
deploy:
- provider: pypi
  user: verdan
  password:
    secure: nKtCI1pEc5uWHW7j3U1f7+WpPXk6qe8uBzgkgwbeekT3LZfK230SMerJnKmQJxl6KZUgSFr+ZbospEwrB25BD4vUal1gCGy+CHqNkWIA/ypFQRuOZN3guR5f9QldprEN4s20IFFs+ehzcXLXe1DCl67p/Yke9TyS1x1jKSJadwCfUgQXtM4XcRvyLXAdWzhJGijvtJxEcyOEBOycdLLwQ2nZHclZaVq7xnWdOoKio4YBLwiRZbBp1IYxyP1+hWj3Berq5QLD6IrrC3b4I7BEoxOncbIFyBXI7KfmmPIg6h41+98u79Ghal7iS0rsJiflaB28ao9bH+kO3+GwHPCn1ASVWzNq+W/xRNg8pCuVS8icuWgUbfaYKrD/K/VvcjTKvrCxJPH7Sw4XmaVTl3SDrr2SQi+1B7bhO5h16fD7RcWmB0kcxXJYW41NRXwVrgCXOngGdy/F1Jv00Vxl39uL9eXeIHaNMuikVfml1I32Kie2Cjyk6emT4O7Zu/zmSQnVHNF/OBI34qUZeyV9gv5g5r+JBd2Nki9omiJ8DT9TDdLB8NP8hKbGIuVRg0QZbnBfXSZczE6PNlM5s1TSPAMG769190Nyh1AeA9Bg+Qv4QKMexaoYbvkkjTHzZ+3xt/yvbrkM4Q9h+nNAE77VDU7Dao3dummtmSarlU73cmrti3A=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: dwarszawski/amundsen-atlas-types
